apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-db-secret
  labels:
    {{- include "eregulations.labels" . | nindent 4 }}
type: Opaque
stringData:
  db-password: {{ .Values.database.password | quote }}
  connection-default: {{ include "eregulations.connectionString" (dict "host" .Values.database.host "port" .Values.database.port "catalog" .Values.database.name "user" .Values.database.user "password" .Values.database.password) | quote }}
  connection-global: {{ include "eregulations.connectionString" (dict "host" .Values.database.host "port" .Values.database.port "catalog" .Values.database.globalName "user" .Values.database.user "password" .Values.database.password) | quote }}
  connection-consistency: {{ include "eregulations.connectionString" (dict "host" .Values.database.host "port" .Values.database.port "catalog" .Values.database.consistencyName "user" .Values.database.user "password" .Values.database.password) | quote }}
