services:
  webapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ${MEDIA_FOLDER}:/app/media:z
    depends_on:
      mssql:
        condition: service_healthy
    environment:
      - ConnectionStrings__DefaultConnection=Data Source=mssql;Initial Catalog=${DATABASE_NAME};User Id=sa;Password=${DATABASE_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True
      - ConnectionStrings__GlobalConnection=Data Source=mssql;Initial Catalog=00-dbe-global;User Id=sa;Password=${DATABASE_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True
      - ConnectionStrings__ConsistencyConnection=Data Source=mssql;Initial Catalog=00-dbe-consistency;User Id=sa;Password=${DATABASE_PASSWORD};MultipleActiveResultSets=true;TrustServerCertificate=True
    networks:
      - app_network

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-eregulations-8
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${DATABASE_PASSWORD}
      - MSSQL_PID=Developer
    volumes:
      - mssql_data:/var/opt/mssql
      - ${DATABASE_FOLDER}:/var/backups:z
    healthcheck:
      test: /opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P "${DATABASE_PASSWORD}" -C -Q "SELECT 1" || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  mssql_data:
